version: '3.8'

services:

  # pickmeapi:
  #   image: 'pickme-api:2'
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - default
  #   depends_on:
  #     - mysqldb

  # en caso de que falle psql probemos con mysql 
  mysqldb:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: menucom_dev
      MYSQL_USER: menucom
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: rootsuper
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - default
